/*
 * Copyright (c) Clarisma / GeoDesk contributors
 *
 * This source code is licensed under the Apache 2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

using GeoDesk.Common.Ast;
using GeoDesk.Common.Store;
using GeoDesk.Feature.Store;

namespace GeoDesk.Feature.Match;

/// <summary>
/// An AST-interpreting <see cref="Matcher"/>: instead of compiling a query's
/// <see cref="Selector"/>/<see cref="TagClause"/>/Expression to a delegate (as
/// <see cref="ExpressionTagMatcher"/> does), it walks the parsed query at runtime against a feature's tag table.
/// It is the fallback used when dynamic code is unavailable (e.g. Native AOT), and a complete implementation
/// in its own right — not a subset.
/// </summary>
/// <remarks>
/// <para>
/// The tag-table scan and the per-value operations (decode-as-number, string/regex comparison) are the
/// shared <see cref="MatcherOps"/> — the same primitives the compiled matcher's tree calls — so the two
/// implementations cannot drift. This matcher supplies only the structure: walk the selector chain (OR),
/// each selector's clauses (AND), and each clause's value expression. Query literals are pre-encoded once at
/// construction (<see cref="_literals"/>, <see cref="_keyNames"/>, <see cref="_regex"/>) so the hot path
/// never allocates; the precomputed tables are read-only afterwards, so one matcher is safe to share across
/// the parallel tile scans of a query.
/// </para>
/// <para>
/// Port-only (no direct Java counterpart): substitutes for the Java bytecode matcher generated by
/// <c>com.geodesk.feature.match.MatcherCoder</c>.
/// </para>
/// </remarks>
internal class AstTagMatcher : TagMatcher
{

    readonly Selector _first;

    // The global-string code of "no", looked up once from the string table (0 if the table has no "no").
    readonly int _valueNo;

    // UTF-8 of every local key name, for MatcherOps.FindTagLocal. Built once, read-only afterwards.
    readonly Dictionary<string, byte[]> _keyNames;

    // A MatchLiteral (text + UTF-8 + global code) per string/global-string literal node, so comparisons
    // allocate nothing per feature. Keyed by node reference.
    readonly Dictionary<Literal, MatchLiteral> _literals;

    // Compiled regexes for the query's ~ / !~ patterns, keyed by pattern. Scoped to this matcher (one query)
    // and read-only after construction — unlike a process-wide static cache, which would grow unbounded.
    readonly Dictionary<string, Regex> _regex;

    /// <remarks>Port-only: builds an interpreting matcher for a query's selector chain.</remarks>
    public AstTagMatcher(Selector first, GlobalStringTable strings) :
        base(AcceptedTypesOf(first), strings, KeyMaskOf(first), KeyMinOf(first))
    {
        _first = first;
        _valueNo = strings.TryGetCode("no", out var noCode) ? noCode : 0;
        (_keyNames, _literals) = BuildLiterals(first);
        _regex = BuildRegexes(first);
    }

    /// <remarks>Port-only: OR of the match-types across the selector chain (mirrors MatcherCoder).</remarks>
    static int AcceptedTypesOf(Selector first)
    {
        var t = 0;
        for (Selector? s = first; s != null; s = s.Next())
            t |= s.MatchTypes();
        return t;
    }

    /// <remarks>Port-only: OR of the key-index bits across the selector chain (mirrors MatcherCoder).</remarks>
    static int KeyMaskOf(Selector first)
    {
        var m = 0;
        for (var s = first; s != null; s = s.Next())
            m |= s.IndexBitsValue();

        return m;
    }

    /// <remarks>Port-only: minimum key-index value across the selector chain (mirrors MatcherCoder).</remarks>
    static int KeyMinOf(Selector first)
    {
        var min = int.MaxValue;
        for (var s = first; s != null; s = s.Next())
            if (s.IndexBitsValue() < min)
                min = s.IndexBitsValue();

        return min;
    }

    /// <remarks>Port-only: pre-encodes local key names (UTF-8) and string/global-string literals, once.</remarks>
    static (Dictionary<string, byte[]>, Dictionary<Literal, MatchLiteral>) BuildLiterals(Selector first)
    {
        var keyNames = new Dictionary<string, byte[]>(StringComparer.Ordinal);
        var literals = new Dictionary<Literal, MatchLiteral>(ReferenceEqualityComparer.Instance);
        for (var sel = first; sel != null; sel = sel.Next())
            for (var clause = sel.FirstClause(); clause != null; clause = clause.Next())
            {
                if (clause.IsLocalKey() && !keyNames.ContainsKey(clause.Name))
                    keyNames[clause.Name] = Encoding.UTF8.GetBytes(clause.Name);
                var exp = clause.Expression();
                if (exp != null)
                    CollectLiterals(exp, literals);
            }

        return (keyNames, literals);
    }

    /// <remarks>Port-only: gathers and pre-encodes the string/global-string literals of an expression tree.</remarks>
    static void CollectLiterals(Expression exp, Dictionary<Literal, MatchLiteral> literals)
    {
        switch (exp)
        {
            case UnaryExpression u:
                CollectLiterals(u.Operand, literals);
                break;
            case BinaryExpression b:
                CollectLiterals(b.Left, literals);
                CollectLiterals(b.Right, literals);
                break;
            case Literal l when (l.Value is string || l.Value is GlobalString) && !literals.ContainsKey(l):
                literals[l] = MakeLiteral(l.Value);
                break;
        }
    }

    /// <remarks>Port-only: a literal carries its global-string code (when it is one) for fast equality.</remarks>
    static MatchLiteral MakeLiteral(object? lit) =>
        lit is GlobalString gs ? new MatchLiteral(gs.StringValue, gs.Value) : new MatchLiteral((string)lit!);

    /// <remarks>Port-only: compiles the query's regex patterns once, keyed by pattern (no static cache).</remarks>
    static Dictionary<string, Regex> BuildRegexes(Selector first)
    {
        var map = new Dictionary<string, Regex>(StringComparer.Ordinal);
        for (var sel = first; sel != null; sel = sel.Next())
            for (var clause = sel.FirstClause(); clause != null; clause = clause.Next())
            {
                var exp = clause.Expression();
                if (exp != null)
                    CollectRegexes(exp, map);
            }

        return map;
    }

    /// <remarks>Port-only: gathers and compiles the patterns of <c>~</c>/<c>!~</c> operators in a tree.</remarks>
    static void CollectRegexes(Expression exp, Dictionary<string, Regex> map)
    {
        switch (exp)
        {
            case UnaryExpression u:
                CollectRegexes(u.Operand, map);
                break;
            case BinaryExpression b:
                if (b.Operator == Operator.MATCH || b.Operator == Operator.NOT_MATCH)
                {
                    var pattern = (string)((Literal)b.Right).Value!;
                    if (!map.ContainsKey(pattern))
                        map[pattern] = new Regex(pattern);
                }
                else
                {
                    CollectRegexes(b.Left, map);
                    CollectRegexes(b.Right, map);
                }
                break;
        }
    }

    /// <remarks>Port-only: implements <c>Matcher.accept</c> by interpreting the query against the feature.</remarks>
    public override bool Accept(Segment segment, int pFeature)
    {
        for (var sel = _first; sel != null; sel = sel.Next())
            if (MatchSelector(sel, segment, pFeature))
                return true;

        return false;
    }

    /// <remarks>Port-only: a selector matches when all of its clauses match.</remarks>
    bool MatchSelector(Selector sel, Segment segment, int pFeature)
    {
        for (var clause = sel.FirstClause(); clause != null; clause = clause.Next())
            if (!MatchClause(clause, segment, pFeature))
                return false;

        return true;
    }

    /// <remarks>Port-only: evaluates a single tag clause against the feature's tags.</remarks>
    bool MatchClause(TagClause clause, Segment segment, int pFeature)
    {
        var tag = clause.IsGlobalKey()
            ? MatcherOps.FindTagGlobal(segment, pFeature, clause.KeyCode())
            : MatcherOps.FindTagLocal(segment, pFeature, _keyNames[clause.Name]);

        var present = tag.Present;
        var isNo = present && tag.Kind == TagValues.GLOBAL_STRING && tag.ValueCode == _valueNo;

        var exp = clause.Expression();
        if (exp == null)
        {
            if (clause.IsKeyRequired())
            {
                // [k]: key present and not "no"
                return present && !isNo;
            }

            // [!k]: key absent or "no"
            return !present || isNo;
        }

        if (clause.IsKeyRequired())
        {
            // [k=v], [k>v], lists, etc.
            // If the key is required *explicitly only* (e.g. [k][k!=v]), the value must
            // also not be "no", in addition to the expression holding.
            var requiredExplicitlyOnly = (clause.Flags() & (TagClause.KEY_REQUIRED_EXPLICITLY | TagClause.KEY_REQUIRED_IMPLICITLY)) == TagClause.KEY_REQUIRED_EXPLICITLY;

            if (requiredExplicitlyOnly)
                return present && !isNo && EvalExpr(exp, tag);

            return present && EvalExpr(exp, tag);
        }

        // [k!=v]: matches if key absent, or expression holds
        if (!present)
            return true;

        return EvalExpr(exp, tag);
    }

    /// <remarks>Port-only: recursively evaluates a clause expression against a located tag value.</remarks>
    bool EvalExpr(Expression exp, TagMatch tag)
    {
        if (exp is UnaryExpression u)
        {
            // only NOT
            return !EvalExpr(u.Operand, tag);
        }

        var b = (BinaryExpression)exp;
        var op = b.Operator;
        if (op == Operator.AND)
            return EvalExpr(b.Left, tag) && EvalExpr(b.Right, tag);
        if (op == Operator.OR)
            return EvalExpr(b.Left, tag) || EvalExpr(b.Right, tag);

        var litNode = (Literal)b.Right;
        var lit = litNode.Value;

        if (op == Operator.LT || op == Operator.LE || op == Operator.GT || op == Operator.GE)
        {
            var d = Convert.ToDouble(lit, CultureInfo.InvariantCulture);
            var tv = MatcherOps.TagDouble(tag.ValueBytes, tag.Kind, tag.ValueCode, globalStrings);
            if (op == Operator.LT)
                return tv < d;
            if (op == Operator.LE)
                return tv <= d;
            if (op == Operator.GT)
                return tv > d;
            return tv >= d;
        }

        if (op == Operator.EQ || op == Operator.NE)
        {
            bool eq = lit is double dd
                ? MatcherOps.TagDouble(tag.ValueBytes, tag.Kind, tag.ValueCode, globalStrings) == dd
                : MatcherOps.TagValueEquals(tag.ValueBytes, tag.Kind, tag.ValueCode, globalStrings, _literals[litNode]);
            return op == Operator.EQ ? eq : !eq;
        }

        if (op == Operator.MATCH)
            return MatcherOps.TagValueMatches(tag.ValueBytes, tag.Kind, tag.ValueCode, globalStrings, _regex[(string)lit!]);
        if (op == Operator.NOT_MATCH)
            return !MatcherOps.TagValueMatches(tag.ValueBytes, tag.Kind, tag.ValueCode, globalStrings, _regex[(string)lit!]);
        if (op == Operator.IN)
            return MatcherOps.TagValueContains(tag.ValueBytes, tag.Kind, tag.ValueCode, globalStrings, _literals[litNode]);
        if (op == QueryParser.STARTS_WITH)
            return MatcherOps.TagValueStartsWith(tag.ValueBytes, tag.Kind, tag.ValueCode, globalStrings, _literals[litNode]);
        if (op == QueryParser.ENDS_WITH)
            return MatcherOps.TagValueEndsWith(tag.ValueBytes, tag.Kind, tag.ValueCode, globalStrings, _literals[litNode]);

        throw new NotSupportedException("Interpreted matcher has no implementation for operator: " + op);
    }

}
