/*
 * Copyright (c) Clarisma / GeoDesk contributors
 *
 * This source code is licensed under the Apache 2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

using GeoDesk.Common.Store;
using GeoDesk.Feature.Store;

namespace GeoDesk.Feature.Match;

/// <summary>
/// A <see cref="Matcher"/> backed by a delegate compiled at runtime from a LINQ expression tree (built by
/// <see cref="ExpressionMatcherCoder"/>) for a specific query — the .NET counterpart of the bytecode
/// class the Java <c>MatcherCoder</c> generates. Per-query literals and regexes are baked into the tree as
/// constants; the global string table is read from the matcher instance via <paramref name="self"/>, exactly
/// as a real method would read <c>this.globalStrings</c>. Like the Java original, the compiled code does not
/// verify the feature type; the inherited <see cref="TagMatcher.AcceptTyped"/> does.
/// </summary>
/// <remarks>Port-only: substitutes for the per-query matcher class generated by the Java MatcherCoder.</remarks>
internal sealed class ExpressionTagMatcher : TagMatcher
{

    /// <summary>
    /// The compiled <see cref="ExpressionTagMatcher.Accept"/> body — the open-instance form of that method, with
    /// the receiver passed explicitly as <paramref name="self"/> (the <c>this</c> an instance method gets
    /// implicitly). Because <see cref="System.Linq.Expressions"/> compiles to a method body rather than a whole
    /// type, this delegate is how we mirror Java's per-query <c>TagMatcher.accept(buf, pos)</c>: same shape, with
    /// <paramref name="self"/> giving the generated code access to instance state (e.g. <see cref="TagMatcher.GlobalStrings"/>).
    /// </summary>
    /// <remarks>Port-only: the .NET stand-in for the generated bytecode <c>accept</c> method.</remarks>
    public delegate bool AcceptDelegate(ExpressionTagMatcher self, Segment segment, int pFeature);

    // The compiled Accept body: tests the feature at pFeature, receiving this matcher as 'self'.
    readonly AcceptDelegate _match;

    /// <remarks>Port-only: wraps a compiled match delegate as a <see cref="Matcher"/>.</remarks>
    public ExpressionTagMatcher(int acceptedTypes, GlobalStringTable strings, int keyMask, int keyMin, AcceptDelegate match) :
        base(acceptedTypes, strings, keyMask, keyMin)
    {
        _match = match;
    }

    /// <remarks>Port-only: invokes the compiled Accept body, passing this matcher as the receiver.</remarks>
    public override bool Accept(Segment segment, int pFeature)
    {
        return _match(this, segment, pFeature);
    }

}
