/*
 * Copyright (c) Clarisma / GeoDesk contributors
 *
 * This source code is licensed under the Apache 2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

using System;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Globalization;
using System.Text.RegularExpressions;
using GeoDesk.Feature.Store;
using NioBuffer = Java.Nio.ByteBuffer;
using GeoDesk.Common.Ast;
using GeoDesk.Common.Math;
using GeoDesk.Common.Util;

namespace GeoDesk.Feature.Match;

/// <summary>
/// An AST-interpreting <see cref="Matcher"/>: instead of compiling a query's
/// <see cref="Selector"/>/<see cref="TagClause"/>/Expression to bytecode (as the Java original
/// does), it walks the parsed query at runtime against a feature's tag table.
///
/// This is the functional, reference implementation (see PORT.md). A runtime compiler
/// (System.Linq.Expressions or Reflection.Emit — undecided) can later be validated against it.
/// </summary>
/// <remarks>
/// Port-only (no direct Java counterpart): substitutes for the Java bytecode matcher generated by
/// <c>com.geodesk.feature.match.MatcherCoder</c>.
/// </remarks>
internal class InterpretedMatcher : TagMatcher
{

    readonly Selector _first;
    readonly int _valueNo;

    static readonly ConcurrentDictionary<string, Regex> RegexCache = new ConcurrentDictionary<string, Regex>();

    /// <remarks>Port-only: builds an interpreting matcher for a query's selector chain.</remarks>
    public InterpretedMatcher(Selector first, string[] globalStrings, int valueNo)
        : base(AcceptedTypesOf(first), globalStrings, KeyMaskOf(first), KeyMinOf(first))
    {
        _first = first;
        _valueNo = valueNo;
    }

    /// <remarks>Port-only: OR of the match-types across the selector chain (mirrors MatcherCoder).</remarks>
    static int AcceptedTypesOf(Selector first)
    {
        var t = 0;
        for (Selector? s = first; s != null; s = s.Next()) t |= s.MatchTypes();
        return t;
    }

    /// <remarks>Port-only: OR of the key-index bits across the selector chain (mirrors MatcherCoder).</remarks>
    static int KeyMaskOf(Selector first)
    {
        var m = 0;
        for (Selector? s = first; s != null; s = s.Next()) m |= s.IndexBitsValue();
        return m;
    }

    /// <remarks>Port-only: minimum key-index value across the selector chain (mirrors MatcherCoder).</remarks>
    static int KeyMinOf(Selector first)
    {
        var min = int.MaxValue;
        for (Selector? s = first; s != null; s = s.Next())
        {
            if (s.IndexBitsValue() < min) min = s.IndexBitsValue();
        }
        return min;
    }

    /// <remarks>Port-only: implements <c>Matcher.accept(ByteBuffer, int)</c> by interpreting the query.</remarks>
    public override bool Accept(NioBuffer buf, int pos)
    {
        var tags = ReadTags(buf, pos);
        for (Selector? sel = _first; sel != null; sel = sel.Next())
        {
            if (MatchSelector(sel, tags)) return true;
        }
        return false;
    }

    /// <remarks>Port-only: a selector matches when all of its clauses match.</remarks>
    bool MatchSelector(Selector sel, List<TagEntry> tags)
    {
        for (TagClause? clause = sel.FirstClause(); clause != null; clause = clause.Next())
        {
            if (!MatchClause(clause, tags)) return false;
        }
        return true;
    }

    /// <remarks>Port-only: evaluates a single tag clause against the feature's tags.</remarks>
    bool MatchClause(TagClause clause, List<TagEntry> tags)
    {
        var t = FindTag(clause, tags);
        var present = t != null;
        var isNo = present && t!.Kind == TagValues.GLOBAL_STRING && t.ValueCode == _valueNo;

        var exp = clause.Expression();
        if (exp == null)
        {
            if (clause.IsKeyRequired())
            {
                // [k]: key present and not "no"
                return present && !isNo;
            }
            // [!k]: key absent or "no"
            return !present || isNo;
        }

        if (clause.IsKeyRequired())
        {
            // [k=v], [k>v], lists, etc.
            // If the key is required *explicitly only* (e.g. [k][k!=v]), the value must
            // also not be "no", in addition to the expression holding.
            var requiredExplicitlyOnly =
                (clause.Flags() & (TagClause.KEY_REQUIRED_EXPLICITLY | TagClause.KEY_REQUIRED_IMPLICITLY))
                == TagClause.KEY_REQUIRED_EXPLICITLY;
            if (requiredExplicitlyOnly) return present && !isNo && EvalExpr(exp, t!);
            return present && EvalExpr(exp, t!);
        }
        // [k!=v]: matches if key absent, or expression holds
        if (!present) return true;
        return EvalExpr(exp, t!);
    }

    /// <remarks>Port-only: locates the tag entry for a clause's key (global code or local name).</remarks>
    TagEntry? FindTag(TagClause clause, List<TagEntry> tags)
    {
        if (clause.IsGlobalKey())
        {
            var code = clause.KeyCode();
            foreach (var e in tags)
            {
                if (e.KeyCode == code) return e;
            }
        }
        else
        {
            var name = clause.Name;
            foreach (var e in tags)
            {
                if (e.KeyCode == 0 && string.Equals(e.KeyString, name, StringComparison.Ordinal)) return e;
            }
        }
        return null;
    }

    /// <remarks>Port-only: recursively evaluates a clause expression against a tag value.</remarks>
    bool EvalExpr(Expression exp, TagEntry t)
    {
        if (exp is UnaryExpression u)
        {
            // only NOT
            return !EvalExpr(u.Operand, t);
        }
        var b = (BinaryExpression)exp;
        var op = b.Operator;
        if (op == Operator.AND) return EvalExpr(b.Left, t) && EvalExpr(b.Right, t);
        if (op == Operator.OR) return EvalExpr(b.Left, t) || EvalExpr(b.Right, t);

        var lit = ((Literal)b.Right).Value;

        if (op == Operator.LT || op == Operator.LE || op == Operator.GT || op == Operator.GE)
        {
            var d = Convert.ToDouble(lit, CultureInfo.InvariantCulture);
            var tv = t.Double();
            if (op == Operator.LT) return tv < d;
            if (op == Operator.LE) return tv <= d;
            if (op == Operator.GT) return tv > d;
            return tv >= d;
        }
        if (op == Operator.EQ || op == Operator.NE)
        {
            bool eq;
            if (lit is double dd)
            {
                eq = t.Double() == dd;
            }
            else
            {
                var s = lit is GlobalString gs ? gs.StringValue : (string)lit!;
                eq = string.Equals(t.String(), s, StringComparison.Ordinal);
            }
            return op == Operator.EQ ? eq : !eq;
        }
        if (op == Operator.MATCH) return RegexMatches(t.String(), (string)lit!);
        if (op == Operator.NOT_MATCH) return !RegexMatches(t.String(), (string)lit!);
        if (op == Operator.IN) return t.String().Contains((string)lit!, StringComparison.Ordinal);
        if (op == MatcherParser.STARTS_WITH) return t.String().StartsWith((string)lit!, StringComparison.Ordinal);
        if (op == MatcherParser.ENDS_WITH) return t.String().EndsWith((string)lit!, StringComparison.Ordinal);
        throw new QueryException("Unsupported operator in interpreted matcher: " + op);
    }

    /// <remarks>Port-only: full-string regex match (Java's <c>Pattern.matches()</c> semantics) with a cache.</remarks>
    static bool RegexMatches(string input, string pattern)
    {
        var rx = RegexCache.GetOrAdd(pattern, p => new Regex(p));
        // Java's Pattern.matches() requires a full-string match.
        var m = rx.Match(input);
        return m.Success && m.Index == 0 && m.Length == input.Length;
    }

    // === Tag-table reading (format from STagTable / MatcherCoder) ===

    /// <remarks>Port-only: reads a feature's tag table into entries (the layout MatcherCoder reads).</remarks>
    List<TagEntry> ReadTags(NioBuffer buf, int pos)
    {
        var entries = new List<TagEntry>();
        var pPtr = pos + 8;
        var taggedPtr = buf.GetInt(pPtr);
        var hasLocalKeys = (taggedPtr & 1) != 0;
        var tagTablePtr = pPtr + (taggedPtr & ~1);

        // Global (common) keys: forward from the anchor
        var p = tagTablePtr;
        for (; ; )
        {
            int key16 = buf.GetChar(p);
            var keyCode = (key16 >> 2) & 0x1fff;
            if (keyCode == 0) break; // empty-table marker / no global keys
            var kind = key16 & 3;
            var wide = (kind & 2) != 0;
            var e = new TagEntry(buf, globalStrings) { Kind = kind, KeyCode = keyCode, KeyString = globalStrings[keyCode] };
            int next;
            if (wide)
            {
                var w = buf.GetInt(p + 2);
                if (kind == TagValues.LOCAL_STRING) e.ValueStringLoc = (p + 2) + w;
                else e.ValueCode = w;
                next = p + 6;
            }
            else
            {
                e.ValueCode = buf.GetChar(p + 2);
                next = p + 4;
            }
            entries.Add(e);
            if ((key16 & 0x8000) != 0) break; // last tag
            p = next;
        }

        // Local (uncommon) keys: backward from the anchor
        if (hasLocalKeys)
        {
            var origin = tagTablePtr & ~3;
            p = tagTablePtr - 4;
            for (; ; )
            {
                var keyPtr = buf.GetInt(p);
                var kind = keyPtr & 3;
                var wide = (kind & 2) != 0;
                var valueSize = wide ? 4 : 2;
                var valuePos = p - valueSize;
                var e = new TagEntry(buf, globalStrings) { Kind = kind, KeyCode = 0 };
                if (wide)
                {
                    var w = buf.GetInt(valuePos);
                    if (kind == TagValues.LOCAL_STRING) e.ValueStringLoc = valuePos + w;
                    else e.ValueCode = w;
                }
                else
                {
                    e.ValueCode = buf.GetChar(valuePos);
                }
                var relPtr = (keyPtr & ~7) >> 1;
                e.KeyString = Bytes.ReadString(buf, origin + relPtr);
                entries.Add(e);
                if ((keyPtr & 4) != 0) break; // first uncommon key
                p = valuePos - 4;
            }
        }

        return entries;
    }

    /// <remarks>Port-only: a decoded tag (key + typed value) used by the interpreter.</remarks>
    sealed class TagEntry
    {

        readonly NioBuffer _buf;
        readonly string[] _globalStrings;

        public int KeyCode;
        public string KeyString = "";
        public int Kind;          // TagValues.NARROW_NUMBER/GLOBAL_STRING/WIDE_NUMBER/LOCAL_STRING
        public int ValueCode;     // narrow number / global string code / wide number code
        public int ValueStringLoc; // for LOCAL_STRING

        /// <remarks>Port-only: captures the buffer and global-string table for lazy value decoding.</remarks>
        public TagEntry(NioBuffer buf, string[] globalStrings)
        {
            _buf = buf;
            _globalStrings = globalStrings;
        }

        /// <remarks>Port-only: decodes the tag value as a string.</remarks>
        public string String()
        {
            switch (Kind)
            {
                case TagValues.NARROW_NUMBER:
                    return (ValueCode + TagValues.MIN_NUMBER).ToString(CultureInfo.InvariantCulture);
                case TagValues.GLOBAL_STRING:
                    return _globalStrings[ValueCode];
                case TagValues.WIDE_NUMBER:
                    return TagValues.WideNumberToString(ValueCode)!;
                default: // LOCAL_STRING
                    return Bytes.ReadString(_buf, ValueStringLoc);
            }
        }

        /// <remarks>Port-only: decodes the tag value as a double.</remarks>
        public double Double()
        {
            switch (Kind)
            {
                case TagValues.NARROW_NUMBER:
                    return ValueCode + TagValues.MIN_NUMBER;
                case TagValues.GLOBAL_STRING:
                    return MathUtils.DoubleFromString(_globalStrings[ValueCode]);
                case TagValues.WIDE_NUMBER:
                    return TagValues.WideNumberToDouble(ValueCode);
                default: // LOCAL_STRING
                    return MathUtils.DoubleFromString(String());
            }
        }

    }

}
