/*
 * Copyright (c) Clarisma / GeoDesk contributors
 *
 * This source code is licensed under the Apache 2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

using System;
using System.Buffers;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

using GeoDesk.Common.Ast;
using GeoDesk.Common.Math;
using GeoDesk.Common.Store;
using GeoDesk.Feature.Store;
using GeoDesk.Feature.Store.Format;

namespace GeoDesk.Feature.Match;

/// <summary>
/// An AST-interpreting <see cref="Matcher"/>: instead of compiling a query's
/// <see cref="Selector"/>/<see cref="TagClause"/>/Expression to bytecode (as the Java original
/// does), it walks the parsed query at runtime against a feature's tag table.
///
/// This is the functional, reference implementation (see PORT.md). A runtime compiler
/// (System.Linq.Expressions or Reflection.Emit — undecided) can later be validated against it.
/// </summary>
/// <remarks>
/// <para>
/// Tags are matched directly off the <see cref="TagTableReader"/> cursor's raw UTF-8 byte spans — no
/// per-feature <c>List</c> of decoded tags, and no <see cref="string"/> is allocated for local keys or
/// values. Query literals are encoded to UTF-8 once at construction (<see cref="_utf8"/>); global-string
/// equality is a global-code comparison; local strings are compared with <c>SequenceEqual</c>. Only the
/// regex operators (and rare number-vs-string operations) transcode to UTF-16, into a stack/pooled
/// buffer rather than the heap. The precomputed tables are read-only after construction, so a single
/// matcher instance is safe to share across the parallel tile scans of one query.
/// </para>
/// <para>
/// Port-only (no direct Java counterpart): substitutes for the Java bytecode matcher generated by
/// <c>com.geodesk.feature.match.MatcherCoder</c>.
/// </para>
/// </remarks>
internal class InterpretedMatcher : TagMatcher
{

    readonly Selector _first;
    readonly int _valueNo;

    // UTF-8 encodings of every local key name and string/global-string literal in the query, computed
    // once at construction so the hot path never allocates. Read-only afterwards (thread-safe).
    readonly Dictionary<string, byte[]> _utf8;

    // Compiled regexes for the query's ~ / !~ patterns, keyed by pattern. Scoped to this matcher (one
    // query) and read-only after construction — unlike a process-wide static cache, which would grow
    // unbounded as distinct patterns are seen over the lifetime of the process.
    readonly Dictionary<string, Regex> _regex;

    /// <remarks>Port-only: builds an interpreting matcher for a query's selector chain.</remarks>
    public InterpretedMatcher(Selector first, string[] globalStrings, int valueNo)
        : base(AcceptedTypesOf(first), globalStrings, KeyMaskOf(first), KeyMinOf(first))
    {
        _first = first;
        _valueNo = valueNo;
        _utf8 = BuildUtf8(first);
        _regex = BuildRegexes(first);
    }

    /// <remarks>Port-only: OR of the match-types across the selector chain (mirrors MatcherCoder).</remarks>
    static int AcceptedTypesOf(Selector first)
    {
        var t = 0;
        for (Selector? s = first; s != null; s = s.Next())
            t |= s.MatchTypes();
        return t;
    }

    /// <remarks>Port-only: OR of the key-index bits across the selector chain (mirrors MatcherCoder).</remarks>
    static int KeyMaskOf(Selector first)
    {
        var m = 0;
        for (var s = first; s != null; s = s.Next())
            m |= s.IndexBitsValue();

        return m;
    }

    /// <remarks>Port-only: minimum key-index value across the selector chain (mirrors MatcherCoder).</remarks>
    static int KeyMinOf(Selector first)
    {
        var min = int.MaxValue;
        for (var s = first; s != null; s = s.Next())
            if (s.IndexBitsValue() < min)
                min = s.IndexBitsValue();

        return min;
    }

    /// <remarks>Port-only: UTF-8-encodes every local key name and string literal in the query, once.</remarks>
    static Dictionary<string, byte[]> BuildUtf8(Selector first)
    {
        var strings = new HashSet<string>(StringComparer.Ordinal);
        for (var sel = first; sel != null; sel = sel.Next())
            for (var clause = sel.FirstClause(); clause != null; clause = clause.Next())
            {
                if (clause.IsLocalKey())
                    strings.Add(clause.Name);
                var exp = clause.Expression();
                if (exp != null)
                    CollectStrings(exp, strings);
            }

        var map = new Dictionary<string, byte[]>(strings.Count, StringComparer.Ordinal);
        foreach (var s in strings)
            map[s] = Encoding.UTF8.GetBytes(s);

        return map;
    }

    /// <remarks>Port-only: gathers the string/global-string literals of an expression tree.</remarks>
    static void CollectStrings(Expression exp, HashSet<string> strings)
    {
        switch (exp)
        {
            case UnaryExpression u:
                CollectStrings(u.Operand, strings);
                break;
            case BinaryExpression b:
                CollectStrings(b.Left, strings);
                CollectStrings(b.Right, strings);
                break;
            case Literal l:
                if (l.Value is string s)
                    strings.Add(s);
                else if (l.Value is GlobalString gs)
                    strings.Add(gs.StringValue);
                break;
        }
    }

    /// <remarks>Port-only: compiles the query's regex patterns once, keyed by pattern (no static cache).</remarks>
    static Dictionary<string, Regex> BuildRegexes(Selector first)
    {
        var map = new Dictionary<string, Regex>(StringComparer.Ordinal);
        for (var sel = first; sel != null; sel = sel.Next())
            for (var clause = sel.FirstClause(); clause != null; clause = clause.Next())
            {
                var exp = clause.Expression();
                if (exp != null)
                    CollectRegexes(exp, map);
            }

        return map;
    }

    /// <remarks>Port-only: gathers and compiles the patterns of <c>~</c>/<c>!~</c> operators in a tree.</remarks>
    static void CollectRegexes(Expression exp, Dictionary<string, Regex> map)
    {
        switch (exp)
        {
            case UnaryExpression u:
                CollectRegexes(u.Operand, map);
                break;
            case BinaryExpression b:
                if (b.Operator == Operator.MATCH || b.Operator == Operator.NOT_MATCH)
                {
                    var pattern = (string)((Literal)b.Right).Value!;
                    if (!map.ContainsKey(pattern))
                        map[pattern] = new Regex(pattern);
                }
                else
                {
                    CollectRegexes(b.Left, map);
                    CollectRegexes(b.Right, map);
                }
                break;
        }
    }

    /// <remarks>Port-only: implements <c>Matcher.accept(ByteBuffer, int)</c> by interpreting the query.</remarks>
    public override bool Accept(Segment segment, int pFeature)
    {
        var span = segment.Memory.Span;
        for (var sel = _first; sel != null; sel = sel.Next())
            if (MatchSelector(sel, span, pFeature))
                return true;

        return false;
    }

    /// <remarks>Port-only: a selector matches when all of its clauses match.</remarks>
    bool MatchSelector(Selector sel, ReadOnlySpan<byte> span, int pFeature)
    {
        for (var clause = sel.FirstClause(); clause != null; clause = clause.Next())
            if (!MatchClause(clause, span, pFeature))
                return false;

        return true;
    }

    /// <remarks>Port-only: evaluates a single tag clause against the feature's tags.</remarks>
    bool MatchClause(TagClause clause, ReadOnlySpan<byte> span, int pFeature)
    {
        var present = FindTag(clause, span, pFeature, out var kind, out var code, out var local);
        var isNo = present && kind == TagValues.GLOBAL_STRING && code == _valueNo;

        var exp = clause.Expression();
        if (exp == null)
        {
            if (clause.IsKeyRequired())
            {
                // [k]: key present and not "no"
                return present && !isNo;
            }

            // [!k]: key absent or "no"
            return !present || isNo;
        }

        if (clause.IsKeyRequired())
        {
            // [k=v], [k>v], lists, etc.
            // If the key is required *explicitly only* (e.g. [k][k!=v]), the value must
            // also not be "no", in addition to the expression holding.
            var requiredExplicitlyOnly = (clause.Flags() & (TagClause.KEY_REQUIRED_EXPLICITLY | TagClause.KEY_REQUIRED_IMPLICITLY)) == TagClause.KEY_REQUIRED_EXPLICITLY;

            if (requiredExplicitlyOnly)
                return present && !isNo && EvalExpr(exp, kind, code, local);

            return present && EvalExpr(exp, kind, code, local);
        }

        // [k!=v]: matches if key absent, or expression holds
        if (!present)
            return true;

        return EvalExpr(exp, kind, code, local);
    }

    /// <remarks>
    /// Port-only: scans the tag-table cursor for the clause's key, returning its value kind, value code,
    /// and (for local strings) raw value bytes. Keys are unique in a tag table, so the first hit wins.
    /// </remarks>
    bool FindTag(TagClause clause, ReadOnlySpan<byte> span, int pFeature,
        out int kind, out int code, out ReadOnlySpan<byte> local)
    {
        var reader = new TagTableReader(span, pFeature);
        if (clause.IsGlobalKey())
        {
            var keyCode = clause.KeyCode();
            while (reader.MoveNext())
            {
                if (reader.KeyCode == keyCode)
                {
                    kind = reader.Kind;
                    code = reader.ValueCode;
                    local = reader.ValueBytes;
                    return true;
                }
            }
        }
        else
        {
            ReadOnlySpan<byte> name = Utf8(clause.Name);
            while (reader.MoveNext())
            {
                if (reader.KeyCode == 0 && reader.KeyBytes.SequenceEqual(name))
                {
                    kind = reader.Kind;
                    code = reader.ValueCode;
                    local = reader.ValueBytes;
                    return true;
                }
            }
        }

        kind = 0;
        code = 0;
        local = default;
        return false;
    }

    /// <remarks>Port-only: recursively evaluates a clause expression against a tag value.</remarks>
    bool EvalExpr(Expression exp, int kind, int code, ReadOnlySpan<byte> local)
    {
        if (exp is UnaryExpression u)
        {
            // only NOT
            return !EvalExpr(u.Operand, kind, code, local);
        }

        var b = (BinaryExpression)exp;
        var op = b.Operator;
        if (op == Operator.AND)
            return EvalExpr(b.Left, kind, code, local) && EvalExpr(b.Right, kind, code, local);
        if (op == Operator.OR)
            return EvalExpr(b.Left, kind, code, local) || EvalExpr(b.Right, kind, code, local);

        var lit = ((Literal)b.Right).Value;

        if (op == Operator.LT || op == Operator.LE || op == Operator.GT || op == Operator.GE)
        {
            var d = Convert.ToDouble(lit, CultureInfo.InvariantCulture);
            var tv = TagDouble(kind, code, local);
            if (op == Operator.LT)
                return tv < d;
            if (op == Operator.LE)
                return tv <= d;
            if (op == Operator.GT)
                return tv > d;
            return tv >= d;
        }

        if (op == Operator.EQ || op == Operator.NE)
        {
            bool eq;
            if (lit is double dd)
            {
                eq = TagDouble(kind, code, local) == dd;
            }
            else
            {
                switch (kind)
                {
                    case TagValues.GLOBAL_STRING:
                        // global value: code comparison when the literal is itself a global string,
                        // otherwise compare against the cached table string (no per-feature alloc).
                        eq = lit is GlobalString gs
                            ? code == gs.Value
                            : string.Equals(globalStrings[code], (string)lit!, StringComparison.Ordinal);
                        break;
                    case TagValues.LOCAL_STRING:
                        eq = local.SequenceEqual(Utf8(LiteralString(lit)));
                        break;
                    default:
                        // number value vs string literal: compare its decimal text (rare).
                        Span<char> nb = stackalloc char[32];
                        eq = FormatNumber(kind, code, nb).SequenceEqual(LiteralString(lit));
                        break;
                }
            }
            return op == Operator.EQ ? eq : !eq;
        }

        if (op == Operator.MATCH)
            return RegexMatches(kind, code, local, (string)lit!);
        if (op == Operator.NOT_MATCH)
            return !RegexMatches(kind, code, local, (string)lit!);
        if (op == Operator.IN)
            return Contains(kind, code, local, (string)lit!);
        if (op == MatcherParser.STARTS_WITH)
            return StartsWith(kind, code, local, (string)lit!);
        if (op == MatcherParser.ENDS_WITH)
            return EndsWith(kind, code, local, (string)lit!);

        throw new QueryException("Unsupported operator in interpreted matcher: " + op);
    }

    /// <remarks>Port-only: decodes the tag value as a double (numeric kinds directly, strings leniently).</remarks>
    double TagDouble(int kind, int code, ReadOnlySpan<byte> local)
    {
        switch (kind)
        {
            case TagValues.NARROW_NUMBER:
                return code + TagValues.MIN_NUMBER;
            case TagValues.GLOBAL_STRING:
                return MathUtils.DoubleFromString(globalStrings[code]);
            case TagValues.WIDE_NUMBER:
                return TagValues.WideNumberToDouble(code);
            default: // LOCAL_STRING
                return MathUtils.DoubleFromString(local);
        }
    }

    /// <remarks>Port-only: <c>str ~ pattern</c> with Java's <c>Pattern.matches()</c> full-string semantics.</remarks>
    bool RegexMatches(int kind, int code, ReadOnlySpan<byte> local, string pattern)
    {
        var rx = _regex[pattern];
        if (kind == TagValues.GLOBAL_STRING)
            return RegexFull(rx, globalStrings[code]);

        if (kind == TagValues.LOCAL_STRING)
        {
            var max = Encoding.UTF8.GetMaxCharCount(local.Length);
            char[]? rented = null;
            Span<char> buf = max <= 256 ? stackalloc char[256] : (rented = ArrayPool<char>.Shared.Rent(max));
            try
            {
                var n = Encoding.UTF8.GetChars(local, buf);
                return RegexFull(rx, buf.Slice(0, n));
            }
            finally
            {
                if (rented != null)
                    ArrayPool<char>.Shared.Return(rented);
            }
        }

        Span<char> nb = stackalloc char[32];
        return RegexFull(rx, FormatNumber(kind, code, nb));
    }

    /// <remarks>Port-only: full-string regex match (Java's <c>Pattern.matches()</c>) over a char span.</remarks>
    static bool RegexFull(Regex rx, ReadOnlySpan<char> input)
    {
        foreach (var m in rx.EnumerateMatches(input))
            return m.Index == 0 && m.Length == input.Length;

        return false;
    }

    /// <remarks>Port-only: <c>str in value</c> — substring test (UTF-8 byte search for local strings).</remarks>
    bool Contains(int kind, int code, ReadOnlySpan<byte> local, string s)
    {
        switch (kind)
        {
            case TagValues.GLOBAL_STRING:
                return globalStrings[code].Contains(s, StringComparison.Ordinal);
            case TagValues.LOCAL_STRING:
                return local.IndexOf(Utf8(s)) >= 0;
            default:
                Span<char> nb = stackalloc char[32];
                return FormatNumber(kind, code, nb).IndexOf(s.AsSpan()) >= 0;
        }
    }

    /// <remarks>Port-only: prefix test (UTF-8 byte compare for local strings).</remarks>
    bool StartsWith(int kind, int code, ReadOnlySpan<byte> local, string s)
    {
        switch (kind)
        {
            case TagValues.GLOBAL_STRING:
                return globalStrings[code].StartsWith(s, StringComparison.Ordinal);
            case TagValues.LOCAL_STRING:
                return local.StartsWith(Utf8(s));
            default:
                Span<char> nb = stackalloc char[32];
                return FormatNumber(kind, code, nb).StartsWith(s.AsSpan());
        }
    }

    /// <remarks>Port-only: suffix test (UTF-8 byte compare for local strings).</remarks>
    bool EndsWith(int kind, int code, ReadOnlySpan<byte> local, string s)
    {
        switch (kind)
        {
            case TagValues.GLOBAL_STRING:
                return globalStrings[code].EndsWith(s, StringComparison.Ordinal);
            case TagValues.LOCAL_STRING:
                return local.EndsWith(Utf8(s));
            default:
                Span<char> nb = stackalloc char[32];
                return FormatNumber(kind, code, nb).EndsWith(s.AsSpan());
        }
    }

    /// <remarks>Port-only: formats a narrow/wide number into the supplied span (mirrors TagValues string forms).</remarks>
    static ReadOnlySpan<char> FormatNumber(int kind, int code, Span<char> buf)
    {
        if (kind == TagValues.NARROW_NUMBER)
        {
            (code + TagValues.MIN_NUMBER).TryFormat(buf, out var n, default, CultureInfo.InvariantCulture);
            return buf.Slice(0, n);
        }

        // WIDE_NUMBER
        var scale = code & 3;
        if (scale == 0)
        {
            var mantissa = (int)((uint)code >> 2) + TagValues.MIN_NUMBER;
            mantissa.TryFormat(buf, out var n, default, CultureInfo.InvariantCulture);
            return buf.Slice(0, n);
        }

        var format = scale == 1 ? "F1" : scale == 2 ? "F2" : "F3";
        TagValues.WideNumberToDouble(code).TryFormat(buf, out var nn, format, CultureInfo.InvariantCulture);
        return buf.Slice(0, nn);
    }

    /// <remarks>Port-only: the textual form of a string/global-string literal.</remarks>
    static string LiteralString(object? lit)
    {
        return lit is GlobalString gs ? gs.StringValue : (string)lit!;
    }

    /// <remarks>Port-only: the precomputed UTF-8 bytes of a query string (local key name or literal).</remarks>
    byte[] Utf8(string s)
    {
        return _utf8[s];
    }

}
