/*
 * Copyright (c) Clarisma / GeoDesk contributors
 *
 * This source code is licensed under the Apache 2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

using System;
using System.IO;

namespace GeoDesk.Tests;

// PORT: Java's TestSettings hard-codes a developer's local GOL path. In the .NET port, GOL fixtures
// live in the test output's Fixtures directory (generated by MSBuild / provided manually). The path
// is returned as-is whether or not the file exists, so a missing fixture surfaces as a normal
// failure (FeatureLibrary throws), exactly like the original.
/// <remarks>Ported from Java <c>com.geodesk.tests.TestSettings</c>.</remarks>
public static class TestSettings
{

    public static string FixturesDir => Path.Combine(AppContext.BaseDirectory, "Fixtures");

    /// <summary>The default test GOL (monaco), resolved to the Fixtures directory.</summary>
    /// <remarks>Ported from Java <c>com.geodesk.tests.TestSettings.golFile()</c>.</remarks>
    public static string GolFile() => Resolve("monaco.gol");

    /// <summary>Resolves a named GOL fixture to its path in the Fixtures directory.</summary>
    public static string Resolve(string name) => Path.Combine(FixturesDir, name);

    /// <remarks>Ported from Java <c>com.geodesk.tests.TestSettings.tileURL()</c>.</remarks>
    public static string? TileUrl() => null;

    /// <remarks>
    /// Ported from Java <c>com.geodesk.tests.TestSettings.outputPath()</c>. The Java original returns
    /// a hard-coded developer path; here it resolves to a created <c>TestOutput</c> directory under
    /// the test assembly's base directory, so debug artifacts land with the test output instead of a
    /// fixed machine path. The trailing separator is preserved (callers use it as a prefix).
    /// </remarks>
    public static string OutputPath()
    {
        var dir = Path.Combine(AppContext.BaseDirectory, "TestOutput");
        Directory.CreateDirectory(dir);
        return dir + Path.DirectorySeparatorChar;
    }

}
