/*
 * Copyright (c) Clarisma / GeoDesk contributors
 *
 * This source code is licensed under the Apache 2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

using System;
using System.IO;

using GeoDesk.Feature;

namespace GeoDesk.Tests.Tests;

// PORT: JUnit @Before/@After become the xUnit constructor / IDisposable. The library is exposed as
// IFeatureQuery so the default-interface query/filter methods are visible (C# does not surface
// default-interface members on the concrete FeatureLibrary type). The monaco GOL fixture is
// generated by the build; if it is absent (e.g. CI run with -p:GenerateGolFixtures=false), `world`
// is null and tests soft-skip with an early `if (world is null) return;` — matching the soft-skip
// convention used by the Feature/* tests.
/// <remarks>Ported from Java <c>com.geodesk.tests.AbstractFeatureTest</c>.</remarks>
public abstract class AbstractFeatureTest : IDisposable
{

    protected readonly IFeatureQuery? world;
    readonly FeatureLibrary? _lib;

    protected AbstractFeatureTest()
    {
        var gol = TestSettings.GolFile();
        if (File.Exists(gol))
        {
            _lib = new FeatureLibrary(gol);
            world = _lib;
        }
    }

    public virtual void Dispose()
    {
        _lib?.Close();
    }

}
